# Generated by Django 5.0.6 on 2024-06-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobinformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('compny_address', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('work_place', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite')], max_length=100, null=True)),
                ('work_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time')], max_length=100, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='static/media')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobRecruitermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('present_address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('instragram', models.CharField(max_length=100, null=True)),
                ('fathers_name', models.CharField(max_length=100, null=True)),
                ('hobby', models.CharField(max_length=100, null=True)),
                ('languages', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobseekerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('fathers_name', models.CharField(max_length=200, null=True)),
                ('hobby', models.CharField(max_length=200, null=True)),
                ('languages', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('education_year', models.CharField(max_length=200, null=True)),
                ('education_institute', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('institute_name', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
